package hr.fer.oprpp1.hw02.prob1;

/**
 * A class that represents a token generated by {@link Lexer}.
 *
 * @see TokenType
 * @see Lexer
 * @see LexerState
 * @see LexerException
 *
 * @version 1.0
 * @author Marko Šelendić
 */
public class Token {
    /**
     * Type of the token.
     */
    private final TokenType type;

    /**
     * Value of the token.
     */
    private final Object value;

    /**
     * Creates a new token with the given type and value.
     *
     * @param type type of the token
     * @param value value of the token
     */
    public Token(TokenType type, Object value) {
        this.type = type;
        this.value = value;
    }

    /**
     * Returns the value of the token.
     *
     * @return value of the token
     */
    public Object getValue() {
        return value;
    }

    /**
     * Returns the type of the token.
     * @return type of the token
     */
    public TokenType getType() {
        return type;
    }
}
