package hr.fer.oprpp1.custom.scripting.lexer;

/**
 * A class that represents a token generated by {@link SmartScriptLexer}.
 *
 * @see SmartScriptTokenType
 * @see SmartScriptLexer
 * @see SmartScriptLexerState
 * @see SmartScriptLexerException
 *
 * @version 1.0
 * @author Marko Šelendić
 */
public class SmartScriptToken {
    /**
     * Type of the token.
     */
    private final SmartScriptTokenType type;

    /**
     * Value of the token.
     */
    private final Object value;

    /**
     * Creates a new token with the given type and value.
     *
     * @param type type of the token
     * @param value value of the token
     */
    public SmartScriptToken(SmartScriptTokenType type, Object value) {
        this.type = type;
        this.value = value;
    }

    /**
     * Returns the value of the token.
     *
     * @return value of the token
     */
    public Object getValue() {
        return value;
    }

    /**
     * Returns the type of the token.
     * @return type of the token
     */
    public SmartScriptTokenType getType() {
        return type;
    }
}
